# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            plone: 4.3
          - python: 2.7.18
            plone: 5.1
          - python: 2.7.18
            plone: 5.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg62 libjpeg62-dev libbz2-dev
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
          command: pyenv -v
      - name: Setup Env
        run: |
          pip install -r requirements.txt coverage==5.3.1
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#test-4.3#test-${{matrix.plone}}#" buildout.cfg 
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            PLONE_VERSION: 4
            continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg62 libjpeg62-dev libbz2-dev
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
          command: pyenv -v
      - name: Setup Env
        run: |
          pip install -r requirements.txt coverage==5.3.1
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-coverage-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-coverage-${{ env.cache-name }}
      - name: buildout
        run: |
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          bin/coverage run bin/test -t !robot
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
